### ISSUE TITLE
[FEAT] "Elastic Stack Monitoring"  dashboard upgrades list

### ISSUE THREAD

**Issue by dbeast-co** [dbeast-co/dbeast-monitor#21]
Version 1.0.3
"Elastic Stack Monitoring"  dashboard upgrades list:
- [x] Remove Logstash hosts limitation in the "Logstash instance status."
- [x] Аdd available storage size in Bytes/KB/MB, etc. #45
- [x] Fix column names in the "Data relocation" panel
- [x] In the "Data relocation" panel, add the query param of the time to seconds and add override for time units
- [x] In the"Index allocation" panel, add the tooltip with the API explanation

Version 1.0.1
- [x] Remove data from the "Tier stats" in case the tier doesn't exist #156
- [x] Add storage and memory per tier status in the "Stack monitoring" dashboard #65 

Fixed in the V-0.7.1
- [x] Set Units for the "Deleted docs" in the "Cluster health" panel
- [x] Add links from the "Data allocation" block - "Data relocation" panel and "Unassigned shards" panel to the Index monitor dashboard
- [x] In the Thread pools block, set the auto time range in all panels
- [x] In the Thread pools block, set the "unlimited" size in the Reject list panel
- [x] In the Thread pools block, fix search rejects graph – incorrect thread pool inside (write instead search)
- [x] Fix Dedicated coordinating panel - in the data path, change to the /_nodes/coordinating_only:true,ml:false 
-------------------------
- [x] Define sorting by name in the Nodes stats
- [x] Add Deleted documents in the "Cluster health" Block
- [x] In the "Thread pools" block set the minimal value to zero
- [x] Change the "Cluster custom settings" to the whole json - get all settings '''json {{{json data }}}'''
- [x] Set the Cache time of the "Data relocation" panel to 0
- [x] Change "cpu" to "CPU" column name in all panels 
- [x]  Add mount points block - Server mount points diagrams based on the Metricbeat indices 
- [x]  Add Thread pools block - Elasticsearch Thread pools block based on the thread pools pipeline #20
