### ISSUE TITLE
[FEAT] Allerts and recommendations dashboard

### ISSUE THREAD

**Issue by dbeast-co** [dbeast-co/dbeast-monitor#57]
The alerts and recommendations dashboard panels list:
**Index Level:**

- [ ] Indices missing compression
- [ ] Indices lacking an Index Lifecycle Management (ILM) policy
- [ ] Absence of 'index.refresh_interval' setting
- [ ] Overuse of default mappings
- [ ] Empty indices
- [ ] Indices without templates
- [ ] Indices without/with missing replicas
- [ ] Older indices containing deleted documents
- [ ] Indices not used for searches, based on recent activity

**Shard Level:**

- [ ] Large or unusually small shards
- [ ] Shards nearing a 200M document count
- [ ] Shards number optimization based on the high search activity
- [ ] Shards number optimization based on high ingest rates

**Node Level:**

- [ ] Thread pool rejections
- [ ] High JVM
- [ ] Low available disk space
- [ ] High "Fetch" operations number from the Cold tier

**Server Level:**

- [ ] Servers operating with swap memory enabled
- [ ] Imbalances between RAM and JVM allocation
- [ ] Servers with high CPU usage, IOWAIT, or low disk space(all mount points)
- [ ] Constant IOPS relative to ingest/search operations

**Tasks Analytics:**

- [ ] Tasks exceeding a certain threshold time
- [ ] Tasks with high number of aggregations levels
- [ ] Optimization for the single/small bulks document writes
- [ ] Optimization for the write bulk size
- [ ] ESQL tasks running across all indices
- [ ] Search tasks spanning high number of indices

**Logstash Pipeline Analytics:**

- [ ] Pipelines with frequent exceptions
- [ ] Pipelines with internal plugins errors
